import Head from "next/head"
import styles from "../styles/Home.module.css"
import MovieCategory from "../components/movies/MovieCategory"
import TvShowCategory from "../components/tvShows/TvShowCategory"
import { getMovies, getTvShows } from "../utils"

export default function Home({ allMovies, allTvShows }) {

  // Make a trending component
  // Think how to get the category of movies .
  
//  Adding pagination into individual pages . in Movies and Tvshows


// Todo:
  
  // Then bookmarks page on every card component it should have a button for delete form 
  //  bookmark onCLick of it should remove the item from bookmarks array.
  
  // Only added moviePage , add to restofpages.

  // And also persist the state using localstorage!!

  // Adding Loading States and Cleaning the look

  // Fucking the Code Tiding and Clean , reuse and DRY . I know that You can do it alot better.


  return (
    <>
      <Head>
        <title>Entertainment App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        {allMovies.map((movies) => {
          return <MovieCategory data={movies} />
        })}

        {allTvShows.map((tvShows) => {
          return <TvShowCategory data={tvShows} />
        })}
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const allMoviesData = await getMovies()
  const alltvShowsData = await getTvShows()

  const allMovies = allMoviesData.map((movie) => movie.data.results)
  const allTvShows = alltvShowsData.map((tvShow) => tvShow.data.results)


  return {
    props: {
      allMovies,
      allTvShows,
    },
  }
}

