import Head from "next/head"
import MovieCategory from "../components/movies/MovieCategory"
import TvShowCategory from "../components/tvShows/TvShowCategory"
import { getMovies, getTvShows } from "../utils"

export default function Home({ allMovies, allTvShows }) {

  // Todos :
    // Clean up the components make single component for both movie and tvshow.
    // Use moblie first Apporach  to make Responsive design.
    // Clean Up the css files to tailwind css.
    // Add the Single page for Categories like Trending, popular ...

  // Todo Features: 
     // Search Functionality and nice to have if to get based on searched query.
    //  Use SWR for server side state .
    // Write Docmentation for the project. things like what you have learned.


  return (
    <>
      <Head>
        <title>Entertainment App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        {allMovies.map((movies) => {
          return <MovieCategory data={movies} />
        })}

        {allTvShows.map((tvShows) => {
          return <TvShowCategory data={tvShows} />
        })}
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const allMoviesData = await getMovies()
  const alltvShowsData = await getTvShows()

  const allMovies = allMoviesData.map((movie) => movie.data.results)
  const allTvShows = alltvShowsData.map((tvShow) => tvShow.data.results)


  return {
    props: {
      allMovies,
      allTvShows
    },
  }
}
